apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadsense-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: roadsense-api
  template:
    metadata:
      labels:
        app: roadsense-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
